#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#
name: Modemfeed CI
on:
  push:
    branches: 
      - master
  # schedule:
  #   - cron: 0 20 * * *
  # release:
  #   types: [published]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget
      - name: Build package feed
        run: |
          touch dep_installed
          ./build.sh -b
      - name: Assemble repository to artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          cp -rp ./packages/ ./artifact/
          if [ -d ./logs/ ]; then
            cp -rp ./logs/ ./artifact/
          fi
      - name: Upload repository to artifact
        uses: actions/upload-artifact@master
        with:
          name: modemfeed-openwrt-repo
          path: ./artifact/
